# Generated by Django 5.0 on 2023-12-14 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DanceStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subscription_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basic_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(related_name='subscribed_studios', to='dance_flow.dancer')),
                ('instructors', models.ManyToManyField(to='dance_flow.instructor')),
            ],
        ),
        migrations.AddField(
            model_name='dancer',
            name='instructors',
            field=models.ManyToManyField(related_name='dancers', to='dance_flow.instructor'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('dancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dance_flow.dancer')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dance_flow.dancestudio')),
            ],
        ),
    ]
